In [ ]:
# The initial command would be the following, but in this case I had to upgrade datasets
# !pip install datasets

!pip install -q --upgrade datasets

## Import a dataset of news headlines in German

In [ ]:
# Load this dataset: https://huggingface.co/datasets/Jotschi/german-news-titles
from datasets import load_dataset

ds = load_dataset("Jotschi/german-news-titles")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/830 [00:00<?, ?B/s]

train_dataset.json: 0.00B [00:00, ?B/s]

test_dataset.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/843 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/257 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

df = pd.DataFrame(ds['train'])
df.head(5)

,titles,text
0,"[Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe, Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main, Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main, Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus, Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann, Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main, Wie die Stadt Frankfurt am Main zur umweltfreundlichen Metropole avanciert: Von ökologischen Gebäuden bis hin zu Radwegen, Die Renaissance des städtischen Lebensraums: Erfolgsgeschichte Frankfurt am Main und ihre Lektionen für andere Städte, Architektur und Stadtentwicklung im Spannungsfeld von Umweltschutz und Lebensqualität - Der Weg zu nachhaltigen urbanen Räumen, Städtisches Wachstum im Einklang mit Umwelt und Nachhaltigkeit: Frankfurt am Main als Vorbild für andere Städte, Vom Hauptbahnhof zum Campus Towers: Die Transformation des Stadtzentrums in Frankfurt am Main, Der Wandel der Architektur und Stadtentwicklung - Frankfurt am Main zeigt, wie es geht, Innovative städtische Projekte: Das Europaviertel und die Campus Towers von Frankfurt am Main überzeugen, Die Zukunft des urbanen Lebensraums - Erfahrungen aus Frankfurt am Main, Wie öffentliche Räume das Leben in Städten bereichern können: Einblicke aus Frankfurt am Main, Von Radwegen bis zu nachhaltiger Bebauung: Frankfurt am Main setzt neue Akzente in der Architektur und Stadtentwicklung, Nachhaltige Architektur und Verkehrsentwicklung - Erfolgsfaktoren für lebenswerte Städte, wie Frankfurt am Main zeigt, Wie Architektur und Stadtentwicklung das Gesicht von Frankfurt am Main verändert haben, Einblicke in moderne urbane Projekte: Das Europaviertel und Campus Towers in Frankfurt am Main, Die Bedeutung von öffentlichen Räumen und nachhaltiger Bebauung für das Wohlbefinden in Städten - Erfahrungen aus Frankfurt am Main]","Die Architektur und Stadtentwicklung sind wichtige Themen, die die Lebensqualität in urbanen Räumen beeinflussen. Immer mehr Städte erkennen dies und legen Wert darauf, nachhaltig und lebenswert zu wachsen. Ein Beispiel für diese positive Entwicklung ist die deutsche Stadt Frankfurt am Main. Hier wurden in den letzten Jahren zahlreiche Projekte umgesetzt, die sich auf eine bessere Integration von öffentlichen Räumen und nachhaltiger Bebauung konzentrieren.\n\nEines der beispielhaftesten Projekte ist das Europaviertel, welches den städtischen Raum neu erfindet. Hier wurden moderne Gebäude errichtet, die sich durch ihre ökologische und energieeffiziente Bauweise auszeichnen. Darüber hinaus wurde darauf geachtet, dass öffentliche Räume wie Parks und Plätze gut in das Gesamtkonzept integriert sind. Dadurch ist es den Menschen möglich, sich in einem natürlichen Umfeld aufzuhalten und dabei dennoch von der Infrastruktur des Stadtzentrums zu profitieren.\n\nEin weiteres herausragendes Projekt in Frankfurt am Main ist die Umgestaltung des ehemaligen Hauptbahnhofgeländes, das nun unter dem Namen ""Campus Towers"" bekannt ist. Hier wurden moderne Bürogebäude errichtet, die sich durch ihre nachhaltige Bauweise und flexible Raumstrukturen auszeichnen. Das Areal beherbergt außerdem ein breites Angebot an Restaurants, Cafés und Geschäften, die den Mitarbeitern der umliegenden Firmen zur Verfügung stehen.\n\nNeben diesen Projekten setzt sich Frankfurt am Main auch für eine nachhaltige Verkehrsentwicklung ein. Hierzu wurde beispielsweise das Radverkehrskonzept ""Radentscheid"" entwickelt, welches den Ausbau von Radwegen und Fahrradabstellanlagen vorsieht. Dadurch soll die Nutzung des Fahrrads in der Stadt gefördert und damit ein Beitrag zum Klimaschutz sowie zur Verbesserung der Luftqualität geleistet werden.\n\nDie Architektur und Stadtentwicklung sind also entscheidend für die Lebensqualität in urbanen Räumen. Frankfurt am Main hat sich hierbei als Vorbild erwiesen, indem es innovative Projekte zur Integration von öffentlichen Räumen sowie nachhaltiger Bebauung umsetzt und den Fokus auf eine nachhaltige Verkehrsentwicklung legt. Weitere Städte sollten sich an diesen Erfolgsbeispielen orientieren, um eine lebenswerte Umgebung für ihre Bürger zu schaffen."
1,"[Beschleunigung des 5G-Rollouts: Bundesregierung setzt auf digitale Transformation und Wettbewerbsfähigkeit, Schnelles Internet für alle: Bundesregierung beschleunigt Einführung von 5G in Deutschland, 5G-Revolution: So will die Bundesregierung den digitalen Wandel beschleunigen, Nationales 5G-Netz: Bundesregierung plant schnelleren Rollout, Die Zukunft des Internets: Bundesregierung treibt Einführung von 5G voran, Vom 4G zum 5G: Wie die Bundesregierung den Sprung in eine neue digitale Ära ermöglicht, Highspeed-Breitband für alle: Bundesregierung beschleunigt 5G-Rollout, Deutschlands Weg ins digitale Zeitalter: Bundesregierung treibt Einführung von 5G voran, Neue Technologien: Bundesregierung setzt auf 5G zur Stärkung des digitalen Marktes, 5G-Revolution: So will Deutschland den Anschluss an das globale Technologiemekka nicht verpassen, Digitaler Wandel in Deutschland: Bundesregierung beschleunigt Einführung von 5G, Schnelles Internet für alle: Bundesregierung plant schnelleren Rollout von 5G-Netzen, Ein Netz für die Zukunft: Bundesregierung treibt Einführung von 5G voran, Deutschland beschleunigt den Weg ins digitale Zeitalter: Die Bundesregierung plant einen schnelleren Rollout von 5G-Netzen, Vom 4G zum 5G: Wie die Bundesregierung den Sprung in eine neue digitale Ära ermöglicht, Highspeed-Breitband für alle: So will Deutschland den Anschluss an das globale Technologiemekka nicht verpassen, Digitaler Wandel in Deutschland: Die Bundesregierung treibt Einführung von 5G voran, Schnelles Internet für alle: Deutschland beschleunigt den Rollout von 5G-Netzen, Neue Technologien: So will Deutschland den Anschluss an das globale Technologiemekka nicht verpassen, Die Zukunft des Internets: Wie die Bundesregierung den Weg ins digitale Zeitalter beschleunigt]","Die Bundesregierung hat heute in einer Pressekonferenz bekannt gegeben, dass sie die Einführung eines 5G-Netzes in Deutschland beschleunigen möchte. Der Schritt erfolgt im Zuge der wachsenden Nachfrage nach schneller und zuverlässiger Internetverbindung sowie zur Stärkung der Wettbewerbsfähigkeit des Landes auf dem globalen Technologiemarkt.\n\nDie Bundesregierung hat eine Reihe von Maßnahmen ergriffen, um die Umsetzung dieses Vorhabens zu erleichtern und den Prozess effektiver zu gestalten. Dazu gehört zum Beispiel die Verbesserung des Zugangs zu öffentlichem Eigentum für Mobilfunkbetreiber sowie die Anpassung von regulatorischen Rahmenbedingungen, um den Aufbau des 5G-Netzes zu erleichtern.\n\nDer Schritt zur Beschleunigung der Einführung des 5G-Netzes ist ein wichtiger Meilenstein in Bezug auf die digitale Transformation Deutschlands. Er hat das Potenzial, den Zugang zu Highspeed-Breitbandinternet für Millionen von Menschen und Unternehmen im Land zu verbessern und somit auch zur Schaffung neuer Arbeitsplätze und wirtschaftlichen Wachstums beizutragen.\n\nDie Bundesregierung ist jedoch sicherlich nicht die einzige, die an einer Beschleunigung des 5G-Rollouts interessiert ist. Auch viele europäische Länder versuchen, den Prozess zu beschleunigen und sich auf die Herausforderungen des digitalen Zeitalters vorzubereiten. In diesem Zusammenhang wurde auch über mögliche Kooperationen zwischen verschiedenen EU-Ländern gesprochen, um gemeinsam an der Schaffung eines effektiven 5G-Netzes zu arbeiten.\n\nTrotz der Fortschritte im Bereich der Digitalisierung bleiben jedoch auch einige Herausforderungen bestehen. So gibt es beispielsweise Bedenken hinsichtlich des Datenschutzes und der Sicherheit von 5G-Technologien, sowie die Frage, ob diese Technologie den Erwartungen gerecht werden kann. Die Bundesregierung hat jedoch versichert, dass sie sich diesen Herausforderungen stellen wird und alles in ihrer Macht Stehende tun wird, um das 5G-Netz so sicher wie möglich zu gestalten.\n\nInsgesamt ist die Beschleunigung des 5G-Rollouts in Deutschland ein wichtiger Schritt auf dem Weg zur digitalen Transformation und zeigt das Engagement der Bundesregierung, den Bürgern und Unternehmen des Landes einen besseren Zugang zu Highspeed-Breitbandinternet zu ermöglichen. Die Einführung dieses Netzes könnte in den kommenden Jahren erhebliche Auswirkungen auf die deutsche Wirtschaft und Gesellschaft haben und somit das Land ins digitale Zeitalter führen."
2,"[Politische Parteien: Stärke und Vielfalt des deutschen Demokratie-Systems, Wahlen und Koalitionen: Das deutsche Parteiensystem im Fokus, Die verschiedenen Facetten des politischen Spektrums in Deutschland, Christdemokraten, Sozialdemokraten und Co.: Wer steht hinter welchen Ideologien?, Vom Umweltschutz bis zur Wirtschaftspolitik: Die Themenvielfalt der deutschen Parteien, Flexibilität in der Zusammenarbeit: Wie politische Gruppen ihre Interessen vertreten können, Das deutsche Modell: Warum das Parteilandschaftssystem hierzulande so erfolgreich ist, Unterschiede und Gemeinsamkeiten: Die ideologischen Ströme in den politischen Lagern, Chancengleichheit, Umweltschutz oder stabile Wirtschaft - welche Werte verfolgen die Parteien?, Von der Gründung bis zur Regierungsbeteiligung: Der Weg einer deutschen Politikpartei, Die Bedeutung kleinerer politischer Gruppen und Sammlungsbewegungen, Das deutsche Modell im Vergleich zu anderen europäischen Ländern, Wie die Zusammenarbeit zwischen den verschiedenen politischen Gruppen funktioniert, Die Bedeutung der Basis: Mitgliedschaft und innerparteiliche Demokratie in Deutschland, Wahlen und Umfragen: Wie sich das Kräfteverhältnis im deutschen Parteiensystem verändert hat, Das deutsche Parlament: Wer sitzt dort, und welche politischen Gruppen sind vertreten?, Die Rolle der Medien bei der Vermittlung von politischen Inhalten und Ideen, Kritik und Selbstkritik: Wie sich die verschiedenen politischen Gruppen weiterentwickeln wollen, Das deutsche Modell im Wandel: Herausforderungen und Chancen für das Parteiensystem, Politische Partizipation in Deutschland: Wie Bürgerinnen und Bürger an der Gestaltung ihres Lebens teilhaben können]","Politische Parteien sind ein wichtiger Bestandteil der demokratischen Prozesse in Deutschland. Sie stellen das Bindeglied zwischen den Bürgern und ihren gewählten Vertretern im Parlament dar, und ermöglichen es damit auch, die verschiedenen Interessen und Meinungen der Bevölkerung effektiv zu vertreten. Die zentrale Aufgabe von politischen Parteien besteht in der Gestaltung und Umsetzung von Politik, wobei sie stets bestrebt sind, das Wohlergehen ihrer Wähler sicherzustellen.\n\nIm deutschen Parteiensystem gibt es eine Vielzahl an politischen Gruppen, die unterschiedliche Ideologien vertreten und somit auch unterschiedliche Konzepte zur Gestaltung der gesellschaftlichen und wirtschaftlichen Verhältnisse haben. Einige dieser Ideologien sind zum Beispiel Sozialdemokratie, Christdemokratie, Liberalismus oder auch Nationalismus.\n\nDie größte politische Partei in Deutschland ist die Christlich Demokratische Union (CDU), welche traditionell eher konservative Werte vertritt und sich für eine stabile Wirtschafts- und Sozialpolitik einsetzt. Daneben gibt es mit der Sozialdemokratischen Partei Deutschlands (SPD) eine weitere große Kraft, die in erster Linie auf soziale Gerechtigkeit und Chancengleichheit abzielt.\n\nWeitere bedeutende politische Gruppen sind zum Beispiel die FDP (Freie Demokratische Partei), die sich vor allem für marktwirtschaftliche Lösungen und weniger Staatseingriffe einsetzt, sowie die Grünen (Bündnis 90/Die Grünen), die insbesondere auf Umweltschutz und soziale Verantwortung fokussiert sind. Auch die Linke, eine eher linke Sammlungsbewegung, hat in den letzten Jahren immer mehr Bedeutung gewonnen.\n\nEin besonderes Merkmal des deutschen Parteiensystems ist jedoch seine Flexibilität und die Möglichkeit der Zusammenarbeit zwischen verschiedenen Gruppen. So können auch kleinere oder neugegründete Partien durch Koalitionen mit größeren politischen Kräften ihre Ideen in den politischen Prozess einbringen, was zu einer breiten Palette an Meinungen und Konzepten führt.\n\nInsgesamt ist das deutsche Parteiensystem von Vielfalt und Offenheit geprägt, wobei stets darauf geachtet wird, dass die unterschiedlichen Interessen der Bevölkerung in den politischen Entscheidungsprozess einfließen können. Die zahlreichen verschiedenen Gruppen und Ideologien ermöglichen es dabei auch, auf neue Herausforderungen und Veränderungen in der Gesellschaft angemessen zu reagieren und stets das Wohlergehen der Menschen im Fokus zu behalten."
3,"[Bundesliga: Die überraschenden Erfolge von Hoffenheim und der langsamere Start des FC Bayern München, Aufstieg von Hoffenheim, Meisterträume bei Dortmund und Leipzig: Highlights aus der Bundesliga-Saison 2021/22, Talente in der Bundesliga: Jude Bellingham und Florian Wirtz im Fokus, Hohe Erwartungen an Bayern München: Kann Trainer Hansi Flick den Meistertitel verteidigen?, Interessante Duelle: Borussia Dortmund vs. RB Leipzig und die Jagd auf den Meistertitel in der Bundesliga-Saison 2021/22, Aufschluss über die Bundesliga-Saison: Talente, Überraschungsteams und der Kampf um die Tabellenspitze, Ein Blick auf die Bundesliga: Welche Teams und Spieler sind diese Saison besonders zu beachten?, Wie steht es um den FC Bayern München in dieser Saison?, Hoffenheim, Dortmund und Leipzig - wer hat das Zeug zum Meistertitel?, Talente und Überraschungsteams: Die Bundesliga-Saison 2021/22 im Fokus, Vom Mittelfeld zur Spitze - wie hat Hoffenheim diesen Erfolgszug erreicht?, Jude Bellingham und Florian Wirtz: Junge deutsche Talente in der Bundesliga-Saison 2021/22, Ein harter Wettbewerb: Bayern München, Dortmund und Leipzig kämpfen um den Meistertitel, Die Bundesliga im Wandel - wer sind die neuen Stars und Teams?, Talente und Trainer: Die Zukunft der Bundesliga-Saison 2021/22, Vom Verfolger zur Favoritenrolle - wie sichert sich Hoffenheim den dritten Tabellenplatz?, Ein spannender Mix: Junge Talente und erfahrene Spieler in der Bundesliga-Saison 2021/22, Das Duell Dortmund gegen Leipzig: Wer holt sich die Tabellenspitze?, Von Führungskräften bis hin zu Rookies - ein Überblick über die wichtigsten Spieler der Bundesliga-Saison 2021/22, Die Bundesliga im Wandel: Neue Talente, Trainer und Teams auf dem Vormarsch]","Die Bundesliga ist in vollem Gange, und es gibt einige spannende Storys, die sich entwickeln. Hier sind einige Highlights, die Fans im Auge behalten sollten.\n\nZuerst ist die überraschende Form der TSG 1899 Hoffenheim zu erwähnen. Nachdem sie in den letzten Jahren eher im Mittelfeld angesiedelt waren, stehen sie jetzt auf dem dritten Tabellenplatz. Trainer Sebastian Hoeneß sollte für diesen Erfolg gelobt werden. Mit einer Mischung aus jungen Talenten und erfahrenen Spielern hat er eine gut funktionierende Truppe zusammengestellt.\n\nEin weiteres Thema ist der langsamere Start von Bayern München. Nachdem sie die vergangenen acht Meisterschaften gewonnen haben, scheint diesmal ein härterer Wettbewerb zu erwarten. Trainer Hansi Flick hat jedoch angekündigt, dass seine Mannschaft bereit ist, den Kampf aufzunehmen und das erste von zwei Titeln in dieser Saison - die deutsche Meisterschaft - anzustreben.\n\nDas Duell zwischen Borussia Dortmund und RB Leipzig bleibt ebenfalls interessant. Beide Teams haben gezeigt, dass sie in der Lage sind, den Meistertitel zu gewinnen, und das Rennen um die Tabellenspitze könnte sich bis zum Ende hinziehen.\n\nZuletzt ist es erfreulich zu sehen, wie viele junge deutsche Talente in der Bundesliga spielen können. Insbesondere Jude Bellingham von Borussia Dortmund und Florian Wirtz vom 1. FC Köln sind zwei Spieler, die in den kommenden Jahren sicherlich auch auf internationaler Ebene eine große Rolle spielen werden.\n\nMit diesen spannenden Themen im Hinterkopf ist es sicherlich ein aufregender Start in die Bundesliga-Saison 2021/22. Fans können gespannt sein, wer am Ende des Wettbewerbs als Sieger hervorgehen wird."
4,"[Geopolitik im 21. Jahrhundert: Herausforderungen und Lösungsansätze, Konflikte, Handel und Umwelt: Die Hauptthemen der modernen Geopolitik, Die Zukunft der Weltmächte: Wie geht es weiter mit Geopolitik?, Globalisierung und Geopolitik: Wie beeinflusst sie unsere Zukunft?, Die Bedeutung des internationalen Handels für die moderne Geopolitik, Umweltgefahren und geopolitische Spannungen im 21. Jahrhundert, Die wichtigsten Akteure in der Weltpolitik: Wer hat das Sagen?, Wirtschaftssanktionen und ihre Auswirkungen auf die Geopolitik, Territorialstreitigkeiten und geopolitische Spannungen: Lösungsmöglichkeiten, Die globale Erwärmung und ihre Bedeutung für die Geopolitik, Handel, Umwelt und Konflikte: Die Hauptthemen der modernen Geopolitik, Die Rolle der internationalen Organisationen bei der Lösung geopolitischer Probleme, Wie die globale Erwärmung das Gleichgewicht von Macht und Ressourcen verändert, Die Zukunft des Welthandels: Geopolitische Herausforderungen und Chancen, Umweltkatastrophen und ihre Auswirkungen auf die Geopolitik im 21. Jahrhundert, Wirtschaftssanktionen: Ein geopolitisches Instrument zur Durchsetzung von Interessen, Die Bedeutung der Umweltzonen für die moderne Geopolitik, Die Herausforderungen des internationalen Handels im Zeitalter der Globalisierung, Die Bedeutung der Energieressourcen für die geopolitische Lage, Die Rolle von Rüstung und Militär in der heutigen Geopolitik]","Die Herausforderungen der Geopolitik im 21. Jahrhundert: Konflikte, Handel und Umwelt\n\nIm Zeitalter der Globalisierung ist die Geopolitik zu einem wichtigen Thema geworden. Immer mehr Länder versuchen, ihren Einfluss auf internationaler Ebene auszuweiten und ihre Machtpositionen zu stärken. In diesem Artikel werden die Hauptherausforderungen der Geopolitik im 21. Jahrhundert analysiert: Konflikte, Handel und Umwelt.\n\nKonflikte sind ein zentrales Element der Geopolitik. Immer wieder kommt es zu Kriegen, Revolten und Territorialstreitigkeiten zwischen Staaten. Die Ursachen solcher Konflikte können vielfältig sein: politische Differenzen, wirtschaftliche Interessen oder religiöse Spannungen. Oft geht es auch darum, die Machtposition des eigenen Landes zu stärken oder den Zugang zu Ressourcen wie Erdöl oder Gas sicherzustellen.\n\nEin weiteres wichtiges Thema ist der internationale Handel. Immer mehr Länder sind in den globalisierten Wirtschaftskreislauf eingebunden und versuchen, ihre wirtschaftlichen Interessen durch Export und Import zu verfolgen. Dabei spielen auch politische Faktoren eine Rolle: Sanktionen oder Wirtschaftssanktionen gegen andere Staaten können den Handel beeinflussen und somit die geopolitische Lage verändern.\n\nSchließlich ist die Umwelt ein zentrales Thema der Geopolitik im 21. Jahrhundert. Die globale Erwärmung, Luftverschmutzung und Wasserknappheit sind Herausforderungen, die alle Staaten betreffen. Gleichzeitig versuchen einige Länder, ihre Ressourcen wie Wasser und Energie zu sichern oder den Zugang zu Umweltzonen wie Meeresgebieten zu kontrollieren. Hierbei können auch Umweltkatastrophen eine wichtige Rolle spielen.\n\nInsgesamt ist die Geopolitik heute ein komplexes Thema, das viele verschiedene Aspekte umfasst. Es gibt nicht nur politische und militärische Konflikte, sondern auch Herausforderungen im Bereich Handel und Umwelt. In einer Zeit der Globalisierung müssen Staaten und internationale Organisationen gemeinsam nach Lösungen suchen, um diese Herausforderungen zu bewältigen und den Frieden und das Wohlergehen aller Menschen zu sichern."

In [ ]:
titles_from_df = df['titles'].tolist()
print(titles_from_df[0])

['Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe', 'Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main', 'Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main', 'Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus', 'Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann', 'Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main', 'Wie die Stadt Frankfurt am Main zur umweltfreundlichen Metropole avanciert: Von ökologischen Gebäuden bis hin zu Radwegen', 'Die Renaissance des städtischen Lebensraums: Erfolgsgeschichte Frankfurt am Main und ihre Lektionen für andere Städte', 'Architektur und Stadtentwicklung im Spannungsfeld von Umweltschutz und Lebensqualität - Der Weg zu nachhaltigen urbanen Räumen', 'Städtisches Wachstum im Einklang mit Umwelt und Nachhaltigkeit: Frankfurt am Main als Vorbild für andere Städte', 'Vom Hauptbahnhof zum Campus Towers: Die Transformation des Stadtzentrums in Frankfurt am Main', 'Der Wandel der Architektur und Stadtentwicklung - Frankfurt am Main zeigt, wie es geht', 'Innovative städtische Projekte: Das Europaviertel und die Campus Towers von Frankfurt am Main überzeugen', 'Die Zukunft des urbanen Lebensraums - Erfahrungen aus Frankfurt am Main', 'Wie öffentliche Räume das Leben in Städten bereichern können: Einblicke aus Frankfurt am Main', 'Von Radwegen bis zu nachhaltiger Bebauung: Frankfurt am Main setzt neue Akzente in der Architektur und Stadtentwicklung', 'Nachhaltige Architektur und Verkehrsentwicklung - Erfolgsfaktoren für lebenswerte Städte, wie Frankfurt am Main zeigt', 'Wie Architektur und Stadtentwicklung das Gesicht von Frankfurt am Main verändert haben', 'Einblicke in moderne urbane Projekte: Das Europaviertel und Campus Towers in Frankfurt am Main', 'Die Bedeutung von öffentlichen Räumen und nachhaltiger Bebauung für das Wohlbefinden in Städten - Erfahrungen aus Frankfurt am Main']

In [ ]:
type(titles_from_df[0])

list

In [ ]:
# titles_from_df is a list of lists
# convert it to a list of strings

titles=[]

for sublist in titles_from_df:
  for item in sublist:
    titles.append(item)

print(titles[0])

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe

In [ ]:
len(titles)

16860

## Apply spaCy's German NER on titles

# Test the small German model

In [ ]:
!python -m spacy download de_core_news_sm

In [ ]:
# Process news titles with spaCy's German language model

import spacy

# Test model on one sentence
nlp_spacy_sm = spacy.load('de_core_news_sm')
doc_sentence = nlp_spacy_sm(titles[0])
print(doc_sentence.text)

# Check the entities
for token in doc_sentence:
  print(token.text, token.ent_type_)

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
Innovative
Architektur
und
Stadtentwicklung
in
Frankfurt LOC
am LOC
Main LOC
:
Das
Europaviertel
und
Campus MISC
Towers MISC
setzen
neue
Maßstäbe

In [ ]:
# Apply the model to the whole document
doc_spacy_sm = [nlp_spacy_sm(title) for title in titles]

In [ ]:
# Visualize a few examples:
for sentence in doc_spacy_sm[:3]:
  print(sentence.text)
  print("---")
  for ent in sentence.ents:
    print(ent.text, ent.label_)
  print("---------------------------------------------------------")

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
---
Frankfurt am Main LOC
Campus Towers MISC
---------------------------------------------------------
Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main
---
Stadt LOC
Frankfurt am Main LOC
---------------------------------------------------------
Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main
---
Campus Towers ORG
Frankfurt am Main LOC
---------------------------------------------------------

In [ ]:
# Save data as a csv file

import pandas as pd

rows=[]

for i, doc in enumerate(doc_spacy_sm):
  for ent in doc.ents:
    rows.append({
        'title': titles[i],
        'entity': ent.text,
        'label': ent.label_
                 })

df_spacy_sm = pd.DataFrame(rows)
df_spacy_sm.to_csv('df_spacy_sm.csv', index=False)

In [ ]:
df_spacy_sm.head(10)

,title,entity,label
0,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Frankfurt am Main,LOC
1,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Campus Towers,MISC
2,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Stadt,LOC
3,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Frankfurt am Main,LOC
4,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Campus Towers,ORG
5,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Frankfurt am Main,LOC
6,Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus,Frankfurt am Main - Nachhaltigkeit,LOC
7,Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann,Radentscheid Frankfurt,PER
8,Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann,Radwegen,LOC
9,Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main,Städten,LOC

# Test the medium German model

In [ ]:
!python -m spacy download de_core_news_md

In [ ]:
nlp_spacy_md = spacy.load('de_core_news_md')

doc_md = [nlp_spacy_md(title) for title in titles]

In [ ]:
# Visualize a few examples:
for sentence in doc_md[:3]:
  print(sentence.text)
  print("---")
  for ent in sentence.ents:
    print(ent.text, ent.label_)
  print("---------------------------------------------------------")

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
---
Frankfurt am Main LOC
Europaviertel LOC
Campus Towers LOC
---------------------------------------------------------
Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main
---
Stadt LOC
---------------------------------------------------------
Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main
---
Europaviertel LOC
Campus Towers LOC
Frankfurt am Main LOC
---------------------------------------------------------

In [ ]:
# Save data as a csv file
rows=[]

for i, doc in enumerate(doc_md):
  for ent in doc.ents:
    rows.append({
        'title': titles[i],
        'entity': ent.text,
        'label': ent.label_
                 })

df_spacy_md = pd.DataFrame(rows)
df_spacy_md.to_csv('df_spacy_md.csv', index=False)

In [ ]:
df_spacy_md.head(10)

,title,entity,label
0,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Frankfurt am Main,LOC
1,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Europaviertel,LOC
2,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Campus Towers,LOC
3,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Stadt,LOC
4,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Europaviertel,LOC
5,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Campus Towers,LOC
6,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Frankfurt am Main,LOC
7,Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus,Frankfurt am Main,LOC
8,Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann,Radentscheid Frankfurt,ORG
9,Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main,Frankfurt am Main,LOC

# Test the large German model

In [ ]:
!python -m spacy download de_core_news_lg

In [ ]:
nlp_spacy_lg = spacy.load('de_core_news_lg')

doc_lg = [nlp_spacy_lg(title) for title in titles]

In [ ]:
# Visualize a few examples:
for sentence in doc_lg[:3]:
  print(sentence.text)
  print("---")
  for ent in sentence.ents:
    print(ent.text, ent.label_)
  print("---------------------------------------------------------")

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
---
Frankfurt am Main LOC
Europaviertel LOC
Campus Towers LOC
---------------------------------------------------------
Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main
---
Stadt LOC
Frankfurt am Main LOC
---------------------------------------------------------
Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main
---
Europaviertel LOC
Campus Towers LOC
Frankfurt am Main LOC
---------------------------------------------------------

In [ ]:
# Save data as a csv file
rows=[]

for i, doc in enumerate(doc_lg):
  for ent in doc.ents:
    rows.append({
        'title': titles[i],
        'entity': ent.text,
        'label': ent.label_
                 })

df_spacy_lg = pd.DataFrame(rows)
df_spacy_lg.to_csv('df_spacy_lg.csv', index=False)

In [ ]:
df_spacy_lg.head(10)

,title,entity,label
0,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Frankfurt am Main,LOC
1,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Europaviertel,LOC
2,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Campus Towers,LOC
3,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Stadt,LOC
4,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Frankfurt am Main,LOC
5,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Europaviertel,LOC
6,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Campus Towers,LOC
7,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Frankfurt am Main,LOC
8,Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus,Frankfurt am Main - Nachhaltigkeit,LOC
9,Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main,Frankfurt am Main,LOC

## Apply stanza's German NER on titles

Refer to [Stanza-Beginners-Guide.ipynb](https://colab.research.google.com/github/stanfordnlp/stanza/blob/master/demo/Stanza_Beginners_Guide.ipynb#scrollTo=HDwRm-KXGcYo) and [Stanza - Named Entity Recognition](https://stanfordnlp.github.io/stanza/ner.html#accessing-named-entity-recogition-ner-tags-for-token)

In [ ]:
!pip install stanza

In [ ]:
import stanza

stanza.download('de')

In [ ]:
nlp_stanza = stanza.Pipeline('de', processors='tokenize, ner')

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language de package default expects mwt, which has been added
INFO:stanza:Loading these models for language: de (German):
============================
| Processor | Package      |
----------------------------
| tokenize  | combined     |
| mwt       | combined     |
| ner       | germeval2014 |
============================

INFO:stanza:Using device: cuda
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!

In [ ]:
doc_sentence_stanza = nlp_stanza(titles[0])

for sent in doc_sentence_stanza.sentences:
  print(sent.text)
  for ent in sent.ents:
    print(ent.text, ent.type)

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
Frankfurt am Main LOC
Campus Towers LOC

In [ ]:
# Use the GPU as the CPU would take a long time to process

nlp_stanza_gpu = stanza.Pipeline('de', processors = 'tokenize,ner', use_gpu= True)

In [ ]:
# Use tqdm to keep track of processing progress

from tqdm import tqdm
doc_stanza = [nlp_stanza_gpu(title) for title in tqdm(titles)]

In [ ]:
# Visualize a few examples:
for sentence in doc_stanza[:3]:
  print(sentence.text)
  print("---")
  for ent in sentence.ents:
      print(ent.text,ent.type)
  print("---------------------------------------------------------")

Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe
---
Frankfurt am Main LOC
Campus Towers LOC
---------------------------------------------------------
Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main
---
Frankfurt am Main LOC
---------------------------------------------------------
Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main
---
Europaviertel LOC
Campus Towers LOC
Frankfurt am Main LOC
---------------------------------------------------------

In [ ]:
# Save data as a csv file
rows=[]

for i, doc in enumerate(doc_stanza):
  for ent in doc.ents:
    rows.append({
        'title': titles[i],
        'entity': ent.text,
        'label': ent.type
                 })

df_stanza = pd.DataFrame(rows)
df_stanza.to_csv('df_stanza.csv', index=False)

In [ ]:
df_stanza.head(10)

,title,entity,label
0,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Frankfurt am Main,LOC
1,Innovative Architektur und Stadtentwicklung in Frankfurt am Main: Das Europaviertel und Campus Towers setzen neue Maßstäbe,Campus Towers,LOC
2,Wie nachhaltige Bebauung und öffentliche Räume das Leben in der Stadt verbessern können - Erfolgsgeschichte Frankfurt am Main,Frankfurt am Main,LOC
3,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Europaviertel,LOC
4,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Campus Towers,LOC
5,"Die Zukunft des urbanen Lebens: Architektur und Stadtentwicklung im Europaviertel und Campus Towers, Frankfurt am Main",Frankfurt am Main,LOC
6,Moderne Gebäude und ökologische Bauweisen in Frankfurt am Main - Nachhaltigkeit im Fokus,Frankfurt am Main,LOC
7,Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann,Radentscheid,LOC
8,Radentscheid Frankfurt: Wie der Ausbau von Radwegen den Verkehr in urbanen Räumen verbessern kann,Frankfurt,LOC
9,Die Bedeutung von öffentlichen Räumen und nachhaltiger Architektur für das Wohlbefinden in Städten - Einblicke aus Frankfurt am Main,Frankfurt am Main,LOC